# Generated by Django 4.2.1 on 2023-05-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_publicacao', models.ImageField(upload_to='publicacoes/', verbose_name='Imagem da publicação')),
                ('link_publicacao', models.CharField(max_length=500, verbose_name='Link da publicacao')),
            ],
        ),
    ]
