# Generated by Django 4.2.1 on 2023-05-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_publicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500, verbose_name='Título do artigo')),
                ('autores', models.TextField(verbose_name='Autores')),
                ('ano', models.IntegerField(verbose_name='Ano de publicação')),
                ('local', models.CharField(max_length=500, verbose_name='Local de publicação')),
                ('link_artigo', models.CharField(max_length=500, verbose_name='Link do artigo')),
            ],
        ),
    ]
