# Generated by Django 4.2.1 on 2023-05-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_artigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoInicialPags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_publicacoes', models.TextField(default='Texto em construção', verbose_name='Texto inicial publicações - Português')),
                ('texto_publicacoes_ing', models.TextField(default='Text under construction', verbose_name='Texto inicial Publicações - Inglês')),
                ('texto_publicacoes_fra', models.TextField(default='Texte en construction', verbose_name='Texto inicial Publicações - Francês')),
                ('texto_pesquisa', models.TextField(default='Texto em construção', verbose_name='Texto inicial pesquisa - Português')),
                ('texto_pesquisa_ing', models.TextField(default='Text under construction', verbose_name='Texto inicial pesquisa - Inglês')),
                ('texto_pesquisa_fra', models.TextField(default='Texte en construction', verbose_name='Texto inicial pesquisa - Francês')),
                ('texto_equipe', models.TextField(default='Texto em construção', verbose_name='Texto inicial equipe - Português')),
                ('texto_equipe_ing', models.TextField(default='Text under construction', verbose_name='Texto inicial equipe - Inglês')),
                ('texto_equipe_fra', models.TextField(default='Texte en construction', verbose_name='Texto inicial equipe - Francês')),
                ('texto_parcerias', models.TextField(default='Texto em construção', verbose_name='Texto inicial parcerias - Português')),
                ('texto_parcerias_ing', models.TextField(default='Text under construction', verbose_name='Texto inicial parcerias - Inglês')),
                ('texto_parcerias_fra', models.TextField(default='Texte en construction', verbose_name='Texto inicial parcerias - Francês')),
                ('texto_divulgacao', models.TextField(default='Texto em construção', verbose_name='Texto inicial divulgacao - Português')),
                ('texto_divulgacao_ing', models.TextField(default='Text under construction', verbose_name='Texto inicial divulgacao - Inglês')),
                ('texto_divulgacao_fra', models.TextField(default='Texte en construction', verbose_name='Texto inicial divulgacao - Francês')),
            ],
        ),
    ]
