# Generated by Django 4.2.1 on 2023-05-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_textoinicialpags'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinhaPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Linha de pesquisa')),
                ('texto', models.TextField(verbose_name='Texto sobre a linha de pesquisa')),
                ('tecnologias', models.TextField(verbose_name='Tecnologias envolvidas (separar por vírgula)')),
            ],
        ),
    ]
