# Generated by Django 4.2.1 on 2023-05-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_linhapesquisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhapesquisa',
            name='codigo_imagem',
            field=models.CharField(default='-', max_length=300, verbose_name='Código da imagem do font-awesome'),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='tecnologias',
            field=models.TextField(default='-', verbose_name='Tecnologias envolvidas (separar por vírgula)'),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='texto',
            field=models.TextField(default='-', verbose_name='Texto sobre a linha de pesquisa'),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='titulo',
            field=models.CharField(default='-', max_length=300, verbose_name='Linha de pesquisa'),
        ),
    ]
