# Generated by Django 4.2.1 on 2023-05-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_linhapesquisa_codigo_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhapesquisa',
            name='texto_fra',
            field=models.TextField(default='-', verbose_name='Texto sobre a linha de pesquisa - Francês'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='texto_ing',
            field=models.TextField(default='-', verbose_name='Texto sobre a linha de pesquisa - Inglês'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='titulo_fra',
            field=models.CharField(default='-', max_length=300, verbose_name='Linha de pesquisa - Francês'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='titulo_ing',
            field=models.CharField(default='-', max_length=300, verbose_name='Linha de pesquisa - Inglês'),
        ),
    ]
