# Generated by Django 4.2.1 on 2023-05-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_linhapesquisa_texto_fra_linhapesquisa_texto_ing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutraAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Curso', 'Curso'), ('Evento', 'Evento'), ('Projeto de extensão', 'Projeto de extensão')], max_length=100, verbose_name='Tipo de ação')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da ação')),
                ('titulo_ing', models.CharField(max_length=100, verbose_name='Título da ação - Inglês')),
                ('titulo_fra', models.CharField(max_length=100, verbose_name='Título da ação - Francês')),
                ('texto', models.TextField(verbose_name='Texto sobre a ação')),
                ('texto_ing', models.TextField(verbose_name='Texto sobre a ação - Inglês')),
                ('texto_fra', models.TextField(verbose_name='Texto sobre a ação - Francês')),
            ],
        ),
    ]
